"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 insole.gltf 
Author: grafi (https://sketchfab.com/zdenkoroman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/insoles-shoe-leather-3d-scan-87693a81c4f9430486be2c24813e98d0
Title: Insoles Shoe Leather 3D Scan
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Insole(props) {
  const { nodes, materials } = useGLTF("/models/insole.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[-0.007, -0.016, 0.018]} rotation={[-0.121, 0, 3.121]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials["vlozka_low-retopo"]}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials["vlozka_low-retopo"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/insole.gltf");
